Links Update
Vito-Research/Vito-Website pull request #12
Opened 2022-06-01 12:57 UTC by AndreasInk

- Coming soon page for any in development links
- SEO meta tags

2022-06-01 16:14 UTC, patrickledew requested changes
Mostly issues with using styles from different components, some best practice stuff. Still have yet to look at the site but i'll do that when i get back from class lol

2022-06-01 16:14 UTC, patrickledew commented on src/components/App.tsx
> +            <div className="App" id="App">
Duplicate App div

2022-06-01 16:14 UTC, patrickledew commented on src/components/ComingSoon.tsx
> +      <h1 className="coming-Header">Coming Soon</h1>
The "apps" class and id should only be for the apps section, not the coming soon page

2022-06-01 16:14 UTC, patrickledew commented on src/components/Footer.tsx
>            </a>
Use the `Link` component from react-router-dom for navigating to pages within the site

2022-06-01 16:14 UTC, patrickledew commented on src/components/ComingSoon.tsx
> +      <div className="apps-feature">
Again, don't use classes meant for other components

2022-06-01 21:00 UTC, AndreasInk commented
@patrickledew I made your suggested changes, please let me know if they are sufficient.

2022-06-02 00:30 UTC, AndreasInk commented
Merged other commits, so it is now more than new links.

Updates include...
Stats on the project and algorithm 
A code contributors page (People.tsx)
Slight verbiage adjustments
Small UI Improvements

2022-06-02 08:24 UTC, patrickledew approved these changes

2022-06-02 08:24 UTC, patrickledew commented
Cool, you're good to merge.

2022-06-02 22:29 UTC, merged